### ISSUE TITLE
tessel update throws an error

### ISSUE THREAD

**Issue by tesseloakland** [tessel/firmware#120]
a@UBUNTU02:~$ tessel update

/home/a/.nvm/v0.10.33/lib/node_modules/tessel/node_modules/usb/node_modules/bindings-shyp/bindings.js:107
  throw err
        ^
Error: Could not locate the bindings file. Tried:
 → /home/a/.nvm/v0.10.33/lib/node_modules/tessel/node_modules/usb/build/usb_bindings.node
 → /home/a/.nvm/v0.10.33/lib/node_modules/tessel/node_modules/usb/build/Debug/usb_bindings.node
 → /home/a/.nvm/v0.10.33/lib/node_modules/tessel/node_modules/usb/build/Release/usb_bindings.node
 → /home/a/.nvm/v0.10.33/lib/node_modules/tessel/node_modules/usb/out/Debug/usb_bindings.node
 → /home/a/.nvm/v0.10.33/lib/node_modules/tessel/node_modules/usb/Debug/usb_bindings.node
 → /home/a/.nvm/v0.10.33/lib/node_modules/tessel/node_modules/usb/out/Release/usb_bindings.node
 → /home/a/.nvm/v0.10.33/lib/node_modules/tessel/node_modules/usb/Release/usb_bindings.node
 → /home/a/.nvm/v0.10.33/lib/node_modules/tessel/node_modules/usb/build/default/usb_bindings.node
 → /home/a/.nvm/v0.10.33/lib/node_modules/tessel/node_modules/usb/compiled/0.10.33/linux/x64/usb_bindings.node
 → /home/a/.nvm/v0.10.33/lib/node_modules/tessel/node_modules/usb/node_modules/usb-shyp-linux-x64/node-v11/usb_bindings.node
 → /home/a/.nvm/v0.10.33/lib/node_modules/tessel/node_modules/usb/node_modules/usb-shyp-linux-x64/usb_bindings.node
    at bindings (/home/a/.nvm/v0.10.33/lib/node_modules/tessel/node_modules/usb/node_modules/bindings-shyp/bindings.js:104:9)
    at Object.<anonymous> (/home/a/.nvm/v0.10.33/lib/node_modules/tessel/node_modules/usb/usb.js:1:124)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/a/.nvm/v0.10.33/lib/node_modules/tessel/src/tessel_usb.js:10:44)
    at Module._compile (module.js:456:26)

**Comment by leighghunt** [comment]
Hi @johnnyman727 - just a quick thought (and I might be barking up the wrong tree) - my tessel installation was all working fine, but I have recently updateded my ````npm```` install to allow non-sudo installs, as per https://github.com/glenpike/npm-g_nosudo (found from http://yeoman.io/codelab/setup.html whilst doing yeoman scaffolding). Node and npm global installs are all working properly without sudo access now.

I've just now tried using tessel again, and I'm now getting the same errors as @tesseloakland when running any of the ````tessel```` commands (````update````, ````list````, ````run```` etc) - could it be a path error, as the packages are now installed in ````~/.npm```` and ````~/.npm-packages````, rather than ````/usr/local/lib/node_modules/````?

Happy to run some tests if you need any more info, as I need to get my tessel install working again :-)

@tesseloakland did/do you have a setup like mine to avoid sudo requirements, whereby some of the ````node```` and ````npm```` files are accessed via symbolic links, and aren't all in the same directory?

**Comment by johnnyman727** [comment]
@kevinmehall would probably be the better person to bring this up with. Kevin, could this be fixed by just rebuilding gyp in the new global Tessel install folder?
